export type LegoSet = {
  setNumber: number;
  price: number;
  year: number;
  url: string;
  image: string;
  alt: string;
  series: string;
};
export const LegoWishlist: LegoSet[] = [
  {
    setNumber: 10297,
    year: 2022,
    price: 848,
    url: "https://zklockow.pl/lego-10297-hotel-butikowy",
    image: "https://zklockow.pl/img/640/lego-10297-hotel-butikowy-1.jpg",
    alt: "Hotel",
    series: "Creator Expert",
  },
  {
    setNumber: 42182,
    year: 2024,
    price: 584,
    url: "https://zklockow.pl/lego-42182-technic-nasa-apollo-pojazd-lrv",
    image:
      "https://zklockow.pl/img/960/lego-technic-42182-nasa-apollo-pojazd-lrv-1.jpg",
    alt: "LRV",
    series: "Technic",
  },
  // {
  //   setNumber: 21348,
  //   year: 2024,
  //   price: 1287,
  //   url: "https://zklockow.pl/lego-21348-ideas-dungeons-dragons-opowiesc-czerwonego-smoka",
  //   image:
  //     "https://zklockow.pl/img/960/lego-ideas-21348-dungeons-dragons-opowiesc-czerwonego-smoka-1.jpg",
  //   alt: "D&D",
  //   series: "Ideas",
  // },
  {
    setNumber: 10350,
    year: 2025,
    price: 999,
    url: "https://zklockow.pl/lego-10350-icons-dom-w-stylu-angielskim",
    image:
      "https://zklockow.pl/img/960/lego-icons-10350-dom-w-stylu-angielskim-1.jpg",
    alt: "Pub",
    series: "Icons",
  },
  // {
  //   setNumber: 10316,
  //   year: 2023,
  //   price: 1799.0,
  //   url: "https://zklockow.pl/lego-10316-icons-wladca-pierscieni-rivendell",
  //   image:
  //     "https://zklockow.pl/img/960/lego-icons-10316-wladca-pierscieni-rivendell-1.jpg",
  //   alt: "Władca Pierścieni: Rivendell™",
  //   series: "Icons",
  // },
  {
    setNumber: 21347,
    year: 2024,
    price: 419.0,
    url: "https://zklockow.pl/lego-21347-ideas-czerwona-londynska-budka-telefoniczna",
    image:
      "https://zklockow.pl/img/960/lego-ideas-21347-czerwona-londynska-budka-telefoniczna-1.jpg",
    alt: "Czerwona londyńska budka telefoniczna",
    series: "Ideas",
  },
  // {
  //   setNumber: 10333,
  //   year: 2024,
  //   price: 1737.1,
  //   url: "https://zklockow.pl/lego-10333-icons-wladca-pierscieni-barad-dur",
  //   image:
  //     "https://zklockow.pl/img/960/lego-icons-10333-wladca-pierscieni-barad-d%C3%BBr-1.jpg",
  //   alt: "Władca Pierścieni: Baraddûr™",
  //   series: "Icons",
  // },
  {
    setNumber: 43227,
    year: 2023,
    price: 449,
    url: "https://zklockow.pl/lego-43227-disney-ikony-zloczyncow",
    image:
      "https://zklockow.pl/img/960/lego-disney-43227-ikony-zloczyncow-1.jpg",
    alt: "Icons",
    series: "Disney",
  },
  {
    setNumber: 10351,
    year: 2025,
    price: 559,
    url: "https://zklockow.pl/lego-10351-icons-sherlock-holmes-book-nook",
    image:
      "https://zklockow.pl/img/960/lego-icons-10351-sherlock-holmes-book-nook-1.jpg",
    alt: "Book Nook",
    series: "Icons",
  },
  {
    setNumber: 21327,
    year: 2022,
    price: 1287.65,
    url: "https://zklockow.pl/lego-21327-ideas-maszyna-do-pisania",
    image:
      "https://zklockow.pl/img/960/lego-21327-ideas-maszyna-do-pisania-1.jpg",
    alt: "Maszyna do pisania",
    series: "Ideas",
  },
  {
    setNumber: 75351,
    year: 2022,
    price: 271.58,
    url: "https://zklockow.pl/lego-75351-star-wars-helm-ksiezniczki-lei-boushh",
    image:
      "https://zklockow.pl/img/960/lego-75351-star-wars-helm-ksiezniczki-lei-boushh-1.jpg",
    alt: "Hełm księżniczki Lei (Boushh)",
    series: "Star Wars",
  },
  {
    setNumber: 75349,
    year: 2022,
    price: 209.9,
    url: "https://zklockow.pl/lego-75349-star-wars-helm-kapitana-rexa",
    image:
      "https://zklockow.pl/img/960/lego-75349-star-wars-helm-kapitana-rexa-1.jpg",
    alt: "Hełm kapitana Rexa",
    series: "Star Wars",
  },
  {
    setNumber: 75350,
    year: 2022,
    price: 292.69,
    url: "https://zklockow.pl/lego-75350-star-wars-helm-dowodcy-klonow-codyego",
    image:
      "https://zklockow.pl/img/960/lego-75350-star-wars-helm-dowodcy-klonow-codyego-1.jpg",
    alt: "Hełm dowódcy klonów Cody'ego",
    series: "Star Wars",
  },
  {
    setNumber: 75343,
    year: 2022,
    price: 369.95,
    url: "https://zklockow.pl/lego-75343-star-wars-helm-mrocznego-szturmowca",
    image:
      "https://zklockow.pl/img/960/lego-75343-star-wars-helm-mrocznego-szturmowca-1.jpg",
    alt: "Hełm mrocznego szturmowca",
    series: "Star Wars",
  },
  {
    setNumber: 75328,
    year: 2022,
    price: 197,
    url: "https://zklockow.pl/lego-75328-star-wars-helm-mandalorianina",
    image:
      "https://zklockow.pl/img/960/lego-75328-star-wars-helm-mandalorianina-1.jpg",
    alt: "Hełm Mandalorianina",
    series: "Star Wars",
  },
  {
    setNumber: 75327,
    year: 2022,
    price: 318,
    url: "https://zklockow.pl/lego-75327-star-wars-helm-lukea-skywalkera-czerwony-piec",
    image:
      "https://zklockow.pl/img/960/lego-75327-star-wars-helm-lukea-skywalkera-czerwony-piec-1.jpg",
    alt: "Hełm Luke'a Skywalkera — Czerwony Pięć",
    series: "Star Wars",
  },
  {
    setNumber: 76187,
    year: 2022,
    price: 409,
    url: "https://zklockow.pl/lego-76187-marvel-venom",
    image: "https://zklockow.pl/img/960/lego-76187-marvel-venom-1.jpg",
    alt: "Venom",
    series: "Marvel",
  },
  {
    setNumber: 75304,
    year: 2022,
    price: 232.5,
    url: "https://zklockow.pl/lego-75304-star-wars-helm-dartha-vadera",
    image:
      "https://zklockow.pl/img/960/lego-75304-star-wars-helm-dartha-vadera-1.jpg",
    alt: "Hełm Dartha Vadera",
    series: "Star Wars",
  },
  {
    setNumber: 76199,
    year: 2022,
    price: 329.99,
    url: "https://zklockow.pl/lego-76199-marvel-carnage",
    image: "https://zklockow.pl/img/960/lego-76199-marvel-carnage-1.jpg",
    alt: "Carnage",
    series: "Marvel",
  },
  {
    setNumber: 75277,
    year: 2022,
    price: 299,
    url: "https://zklockow.pl/lego-75277-star-wars-helm-boby-fetta",
    image:
      "https://zklockow.pl/img/960/lego-75277-star-wars-helm-boby-fetta-1.jpg",
    alt: "Hełm Boby Fetta",
    series: "Star Wars",
  },
  {
    setNumber: 10275,
    year: 2022,
    price: 399,
    url: "https://zklockow.pl/lego-10275-elfi-dom-swiateczny",
    image: "https://zklockow.pl/img/960/lego-10275-elfi-dom-swiateczny-1.jpg",
    alt: "Elfi dom świąteczny",
    series: "Creator Expert",
  },
  {
    setNumber: 10370,
    year: 2022,
    price: 999.99,
    url: "https://zklockow.pl/lego-10370-icons-gwiazda-betlejemska",
    image:
      "https://zklockow.pl/img/960/lego-icons-10370-gwiazda-betlejemska-1.jpg",
    alt: "Gwiazda",
    series: "Icons",
  },
  {
    setNumber: 10311,
    year: 2022,
    price: 149.97,
    url: "https://zklockow.pl/lego-10311-orchidea",
    image: "https://zklockow.pl/img/960/lego-icons-10311-orchidea-1.jpg",
    alt: "Orchidea",
    series: "Icons",
  },
  {
    setNumber: 10369,
    year: 2022,
    price: 89.9,
    url: "https://zklockow.pl/lego-10369-icons-kwiat-sliwy",
    image: "https://zklockow.pl/img/960/lego-icons-10369-kwiat-sliwy-1.jpg",
    alt: "Kwiat śliwy",
    series: "Icons",
  },
  {
    setNumber: 10295,
    year: 2022,
    price: 539.0,
    url: "https://zklockow.pl/lego-10295-porsche-911",
    image: "https://zklockow.pl/img/960/lego-creator-10295-porsche-911-1.jpg",
    alt: "Porsche 911",
    series: "Creator Expert",
  },
  {
    setNumber: 10343,
    year: 2022,
    price: 82.0,
    url: "https://zklockow.pl/lego-10343-botanicals-mala-orchidea",
    image:
      "https://zklockow.pl/img/960/lego-botanicals-10343-mala-orchidea-1.jpg",
    alt: "Mała orchidea",
    series: "Botanicals",
  },
  {
    setNumber: 10331,
    year: 2022,
    price: 154.0,
    url: "https://zklockow.pl/lego-10331-icons-zimorodek",
    image: "https://zklockow.pl/img/960/lego-icons-10331-zimorodek-1.jpg",
    alt: "Zimorodek",
    series: "Icons",
  },
  {
    setNumber: 76419,
    year: 2022,
    price: 571.85,
    url: "https://zklockow.pl/lego-76419-harry-potter-zamek-hogwart-i-blonia",
    image:
      "https://zklockow.pl/img/960/lego-harry-potter-76419-zamek-hogwart-i-blonia-1.jpg",
    alt: "Zamek Hogwart i błonia",
    series: "Harry Potter",
  },
  {
    setNumber: 76414,
    year: 2022,
    price: 329.0,
    url: "https://zklockow.pl/lego-76414-harry-potter-expecto-patronum",
    image:
      "https://zklockow.pl/img/960/lego-harry-potter-76414-expecto-patronum-1.jpg",
    alt: "Expecto Patronum",
    series: "Harry Potter",
  },
  {
    setNumber: 21342,
    year: 2022,
    price: 303.89,
    url: "https://zklockow.pl/lego-21342-ideas-kolekcja-owadow",
    image: "https://zklockow.pl/img/960/lego-ideas-21342-kolekcja-owadow-1.jpg",
    alt: "Kolekcja owadów",
    series: "Ideas",
  },
  {
    setNumber: 10266,
    year: 2022,
    price: 449.99,
    url: "https://zklockow.pl/lego-10266-creator-expert-ladownik-ksiezycowy-apollo-11-nasa",
    image:
      "https://zklockow.pl/img/960/lego-creator-expert-10266-ladownik-ksiezycowy-apollo-11-nasa-1.jpg",
    alt: "Lądownik księżycowy Apollo 11 NASA",
    series: "Creator Expert",
  },
  {
    setNumber: 31133,
    year: 2022,
    price: 69.9,
    url: "https://zklockow.pl/lego-31133-creator-3-w-1-bialy-krolik",
    image:
      "https://zklockow.pl/img/960/lego-creator-3-w-1-31133-bialy-krolik-1.jpg",
    alt: "Biały królik",
    series: "Creator 3 in 1",
  },
  {
    setNumber: 76191,
    year: 2022,
    price: 287.99,
    url: "https://zklockow.pl/lego-76191-marvel-rekawica-nieskonczonosci",
    image:
      "https://zklockow.pl/img/960/lego-marvel-76191-rekawica-nieskonczonosci-1.jpg",
    alt: "Rękawica Nieskończoności",
    series: "Marvel",
  },
  {
    setNumber: 75330,
    year: 2022,
    price: 999.99,
    url: "https://zklockow.pl/lego-75330-star-wars-diorama-sala-tronu-imperatora",
    image:
      "https://zklockow.pl/img/960/lego-star-wars-75330-diorama-sala-tronu-imperatora-1.jpg",
    alt: "Diorama: Sala Tronu Imperatora",
    series: "Star Wars",
  },

  {
    setNumber: 6103,
    year: 1988,
    price: 0,
    url: "https://brickset.com/sets/6103-1",
    image: "https://images.brickset.com/sets/images/6103-1.jpg",
    alt: "Castle Mini Figures",
    series: "Castle",
  },
  {
    setNumber: 6703,
    year: 1988,
    price: 0,
    url: "https://brickset.com/sets/6703-1",
    image: "https://images.brickset.com/sets/images/6703-1.jpg",
    alt: "Minifig Pack",
    series: "Space",
  },
  {
    setNumber: 8712,
    year: 1988,
    price: 0,
    url: "https://brickset.com/sets/8712-1",
    image: "https://images.brickset.com/sets/images/8712-1.jpg",
    alt: "Technic Figures",
    series: "Technic",
  },
  {
    setNumber: 6257,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6257-1",
    image: "https://images.brickset.com/sets/images/6257-1.jpg",
    alt: "Castaway's Raft",
    series: "Pirates",
  },
  {
    setNumber: 6660,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6660-1",
    image: "https://images.brickset.com/sets/images/6660-1.jpg",
    alt: "Hook & Haul Wrecker",
    series: "Town",
  },
  {
    setNumber: 6482,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6482-1",
    image: "https://images.brickset.com/sets/images/6482-1.jpg",
    alt: "Rescue Helicopter",
    series: "Town",
  },
  {
    setNumber: 6481,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6481-1",
    image: "https://images.brickset.com/sets/images/6481-1.jpg",
    alt: "Construction Crew",
    series: "Town",
  },
  {
    setNumber: 6850,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6850-1",
    image: "https://images.brickset.com/sets/images/6850-1.jpg",
    alt: "Auxiliary Patroller",
    series: "Space",
  },
  {
    setNumber: 8024,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/8024-1",
    image: "https://images.brickset.com/sets/images/8024-1.jpg",
    alt: "Universal Set",
    series: "Technic",
  },
  {
    setNumber: 6923,
    year: 1983,
    price: 0,
    url: "https://brickset.com/sets/6923-1",
    image: "https://images.brickset.com/sets/images/6923-1.jpg",
    alt: "Particle Ioniser",
    series: "Space",
  },
  {
    setNumber: 6833,
    year: 1987,
    price: 0,
    url: "https://brickset.com/sets/6833-1",
    image: "https://images.brickset.com/sets/images/6833-1.jpg",
    alt: "Beacon Tracer",
    series: "Space",
  },
  {
    setNumber: 6644,
    year: 1988,
    price: 0,
    url: "https://brickset.com/sets/6644-1",
    image: "https://images.brickset.com/sets/images/6644-1.jpg",
    alt: "Road Rebel",
    series: "Town",
  },
  {
    setNumber: 6672,
    year: 1986,
    price: 0,
    url: "https://brickset.com/sets/6672-1",
    image: "https://images.brickset.com/sets/images/6672-1.jpg",
    alt: "Tow Truck",
    series: "Town",
  },
  {
    setNumber: 6353,
    year: 1988,
    price: 0,
    url: "https://brickset.com/sets/6353-1",
    image: "https://images.brickset.com/sets/images/6353-1.jpg",
    alt: "Coastal Cutter",
    series: "Town",
  },
  {
    setNumber: 6532,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6532-1",
    image: "https://images.brickset.com/sets/images/6532-1.jpg",
    alt: "Diesel Dumper",
    series: "Town",
  },
  {
    setNumber: 8720,
    year: 1991,
    price: 0,
    url: "https://brickset.com/sets/8720-1",
    image: "https://images.brickset.com/sets/images/8720-1.jpg",
    alt: "Technic Figures",
    series: "Technic",
  },
  {
    setNumber: 6704,
    year: 1989,
    price: 0,
    url: "https://brickset.com/sets/6704-1",
    image: "https://images.brickset.com/sets/images/6704-1.jpg",
    alt: "Minifig Pack",
    series: "Space",
  },
  {
    setNumber: 6534,
    year: 1992,
    price: 0,
    url: "https://brickset.com/sets/6534-1",
    image: "https://images.brickset.com/sets/images/6534-1.jpg",
    alt: "Beach Bandit",
    series: "Town",
  },
  {
    setNumber: 6814,
    year: 1990,
    price: 0,
    url: "https://brickset.com/sets/6814-1",
    image: "https://images.brickset.com/sets/images/6814-1.jpg",
    alt: "Ice Tunnelator",
    series: "Space",
  },
  {
    setNumber: 10357,
    year: 2025,
    price: 669,
    url: "https://zklockow.pl/lego-10357-icons-shelby-cobra-427-s-c",
    image:
      "https://zklockow.pl/img/960/lego-icons-10357-shelby-cobra-427-s-c-1.jpg",
    alt: "Cobra",
    series: "Icons",
  },
  {
    setNumber: 40751,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-40751-brickheadz-legolas-i-gimli",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40751-legolas-i-gimli-1.jpg",
    alt: "Legolas i Gimli",
    series: "BrickHeadz",
  },
  {
    setNumber: 40673,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-40673-brickheadz-myszka-miki-w-stroju-na-wiosenny-festiwal",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40673-myszka-miki-w-stroju-na-wiosenny-festiwal-1.jpg",
    alt: "Myszka Miki wiosenny festiwal",
    series: "BrickHeadz",
  },
  {
    setNumber: 40674,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-40674-brickheadz-stitch",
    image: "https://zklockow.pl/img/960/lego-brickheadz-40674-stitch-1.jpg",
    alt: "Stitch",
    series: "BrickHeadz",
  },
  {
    setNumber: 40631,
    year: 2023,
    price: 0,
    url: "https://zklockow.pl/lego-40631-brickheadz-gandalf-szary-i-balrog",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40631-gandalf-szary-i-balrog-1.jpg",
    alt: "Gandalf Szary i Balrog",
    series: "BrickHeadz",
  },
  {
    setNumber: 40622,
    year: 2023,
    price: 0,
    url: "https://zklockow.pl/lego-40622-brickheadz-disney-100-urodziny",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40622-disney-100-urodziny-1.jpg",
    alt: "Disney",
    series: "BrickHeadz",
  },
  {
    setNumber: 40620,
    year: 2023,
    price: 0,
    url: "https://zklockow.pl/lego-40620-brickheadz-cruella-i-diabolina",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40620-cruella-i-diabolina-1.jpg",
    alt: "Cruella i Diabolina",
    series: "BrickHeadz",
  },
  {
    setNumber: 40615,
    year: 2023,
    price: 0,
    url: "https://zklockow.pl/lego-40615-brickheadz-tuskenski-rabus",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40615-tuskenski-rabus-1.jpg",
    alt: "Tuskeński rabuś",
    series: "BrickHeadz",
  },
  {
    setNumber: 40547,
    year: 2022,
    price: 0,
    url: "https://zklockow.pl/lego-40547-brickheadz-obi-wan-kenobi-i-darth-vader",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40547-obi-wan-kenobi-i-darth-vader-1.jpg",
    alt: "ObiWan Kenobi i Darth Vader",
    series: "BrickHeadz",
  },
  {
    setNumber: 40550,
    year: 2022,
    price: 0,
    url: "https://zklockow.pl/lego-40550-brickheadz-chip-i-dale",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40550-chip-i-dale-1.jpg",
    alt: "Chip i Dale",
    series: "BrickHeadz",
  },
  {
    setNumber: 40539,
    year: 2022,
    price: 0,
    url: "https://zklockow.pl/lego-40539-brickheadz-ahsoka-tano",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40539-ahsoka-tano-1.jpg",
    alt: "Ahsoka Tano",
    series: "BrickHeadz",
  },
  {
    setNumber: 40421,
    year: 2021,
    price: 0,
    url: "https://zklockow.pl/lego-40421-brickheadz-belle-bottom-kevin-bob",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40421-belle-bottom-kevin-i-bob-1.jpg",
    alt: "Belle Bottom, Kevin i Bob",
    series: "BrickHeadz",
  },
  {
    setNumber: 40476,
    year: 2021,
    price: 0,
    url: "https://zklockow.pl/lego-40476-brickheadz-kaczka-daisy",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40476-kaczka-daisy-1.jpg",
    alt: "Kaczka Daisy",
    series: "BrickHeadz",
  },
  {
    setNumber: 40477,
    year: 2021,
    price: 0,
    url: "https://zklockow.pl/lego-40477-brickheadz-sknerus-mckwacz-hyzio-dyzio-zyzio",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40477-sknerus-mckwacz-hyzio-dyzio-i-zyzio-1.jpg",
    alt: "Sknerus McKwacz z H,D,Z",
    series: "BrickHeadz",
  },
  {
    setNumber: 21042,
    year: 2018,
    price: 439.99,
    url: "https://zklockow.pl/lego-21042-architecture-statua-wolnosci",
    image:
      "https://zklockow.pl/img/960/lego-architecture-21042-statua-wolnosci-1.jpg",
    alt: "Statua Wolności",
    series: "Architecture",
  },
  {
    setNumber: 75429,
    year: 2025,
    price: 319.89,
    url: "https://zklockow.pl/lego-75429-star-wars-helm-operatora-at-at",
    image:
      "https://zklockow.pl/img/960/lego-star-wars-75429-helm-operatora-at-at-1.jpg",
    alt: "Hełm operatora AT-AT",
    series: "Star Wars",
  },
  {
    setNumber: 21061,
    year: 2024,
    price: 698.99,
    url: "https://zklockow.pl/lego-21061-architecture-notre-dame-w-paryzu",
    image:
      "https://zklockow.pl/img/960/lego-architecture-21061-notre-dame-w-paryzu-1.jpg",
    alt: "NotreDame w Paryżu",
    series: "Architecture",
  },
  {
    setNumber: 77071,
    year: 2024,
    price: 174.99,
    url: "https://zklockow.pl/lego-77071-fortnite-lama-zaopatrzeniowa",
    image:
      "https://zklockow.pl/img/960/lego-fortnite-77071-lama-zaopatrzeniowa-1.jpg",
    alt: "Lama Zaopatrzeniowa",
    series: "Fortnite",
  },

  {
    setNumber: 40443,
    year: 2021,
    price: 0,
    url: "https://zklockow.pl/lego-40443-brickheadz-papuzka",
    image: "https://zklockow.pl/img/960/lego-brickheadz-40443-papuzka-1.jpg",
    alt: "papga",
    series: "BrickHeadz",
  },
  {
    setNumber: 75317,
    year: 2020,
    price: 0,
    url: "https://zklockow.pl/lego-75317-brickheadz-mandalorianin-i-dziecko",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-75317-mandalorianin-i-dziecko-3.jpg",
    alt: "GiM",
    series: "BrickHeadz",
  },
  {
    setNumber: 40377,
    year: 2020,
    price: 0,
    url: "https://zklockow.pl/lego-40377-brickheadz-kaczor-donald",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40377-kaczor-donald-0.jpg",
    alt: "Donald",
    series: "BrickHeadz",
  },
  {
    setNumber: 40378,
    year: 2020,
    price: 0,
    url: "https://zklockow.pl/lego-40378-brickheadz-goofy-i-pluto",
    image:
      "https://zklockow.pl/img/960/lego-brickheadz-40378-goofy-i-pluto-0.jpg",
    alt: "PiG",
    series: "BrickHeadz",
  },
  {
    setNumber: 6081,
    year: 1990,
    price: 0,
    url: "https://brickset.com/sets/6081-1/King-s-Mountain-Fortress",
    image: "https://images.brickset.com/sets/images/6081-1.jpg",
    alt: "Mountais Castle",
    series: "Castle",
  },
  {
    setNumber: 31147,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-31147-creator-3-w-1-aparat-w-stylu-retro",
    image:
      "https://zklockow.pl/img/960/lego-creator-3-w-1-31147-aparat-w-stylu-retro-1.jpg",
    alt: "Photo",
    series: "Creator 3 in 1",
  },
  {
    setNumber: 10457,
    year: 2025,
    price: 0,
    url: "https://zklockow.pl/lego-10457-disney-przyjecie-urodzinowe-kubusia-puchatka",
    image:
      "https://zklockow.pl/img/960/lego-disney-10457-przyjecie-urodzinowe-kubusia-puchatka-1.jpg",
    alt: "Puch",
    series: "Duplo",
  },
  {
    setNumber: 10431,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-10431-duplo-ogrod-i-domek-na-drzewie-peppy",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10431-ogrod-i-domek-na-drzewie-peppy-1.jpg",
    alt: "Pepa",
    series: "Duplo",
  },
  {
    setNumber: 10982,
    year: 2023,
    price: 0,
    url: "https://zklockow.pl/lego-10982-duplo-traktor-z-warzywami-i-owocami",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10982-traktor-z-warzywami-i-owocami-1.jpg",
    alt: "Traktor",
    series: "Duplo",
  },
  {
    setNumber: 10412,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-10412-duplo-pociag-ze-zwierzatkami",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10412-pociag-ze-zwierzatkami-1.jpg",
    alt: "Pociag",
    series: "Duplo",
  },
  {
    setNumber: 10965,
    year: 2022,
    price: 0,
    url: "https://zklockow.pl/lego-10965-duplo-zabawa-w-kapieli-plywajacy-pociag-ze-zwierzatkami",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10965-zabawa-w-kapieli-plywajacy-pociag-ze-zwierzatkami-1.jpg",
    alt: "Wanna",
    series: "Duplo",
  },
  {
    setNumber: 10422,
    year: 2025,
    price: 0,
    url: "https://zklockow.pl/lego-10442-duplo-rodziny-dzikich-zwierzat-pingwiny-i-lwy",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10442-rodziny-dzikich-zwierzat-pingwiny-i-lwy-1.jpg",
    alt: "Zoo",
    series: "Duplo",
  },
  {
    setNumber: 10419,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-10419-duplo-opieka-nad-pszczolami-i-ulami",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10419-opieka-nad-pszczolami-i-ulami-1.jpg",
    alt: "Bee",
    series: "Duplo",
  },
  {
    setNumber: 10418,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-10418-duplo-elza-i-bruni-w-zaczarowanym-lesie",
    image:
      "https://zklockow.pl/img/960/lego-duplo-10418-elza-i-bruni-w-zaczarowanym-lesie-1.jpg",
    alt: "Elsa",
    series: "Duplo",
  },
  {
    setNumber: 43230,
    year: 2023,
    price: 0,
    url: "https://zklockow.pl/lego-43230-disney-kamera-walta-disneya",
    image:
      "https://zklockow.pl/img/960/lego-disney-43230-kamera-walta-disneya-1.jpg",
    alt: "Kamera",
    series: "Disney",
  },
  {
    setNumber: 42179,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-42179-technic-planeta-ziemia-i-ksiezyc-na-orbicie",
    image:
      "https://zklockow.pl/img/960/lego-technic-42179-planeta-ziemia-i-ksiezyc-na-orbicie-1.jpg",
    alt: "Ziemia",
    series: "Technic",
  },
  {
    setNumber: 21325,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-21325-ideas-sredniowieczna-kuznia",
    image:
      "https://zklockow.pl/img/960/lego-ideas-21325-sredniowieczna-kuznia-1.jpg",
    alt: "Kużnia",
    series: "Ideas",
  },
  {
    setNumber: 43249,
    year: 2024,
    price: 0,
    url: "https://zklockow.pl/lego-43249-disney-stitch",
    image: "https://zklockow.pl/img/960/lego-disney-43249-stitch-1.jpg",
    alt: "Stitch",
    series: "Disney",
  },
  // {
  //   setNumber: 21063,
  //   year: 2025,
  //   price: 949,
  //   url: "https://zklockow.pl/lego-21063-architecture-zamek-neuschwanstein",
  //   image:
  //     "https://zklockow.pl/img/960/lego-architecture-21063-zamek-neuschwanstein-1.jpg",
  //   alt: "Stitch",
  //   series: "Architecture",
  // },
  {
    setNumber: 75415,
    year: 2025,
    price: 239,
    url: "https://zklockow.pl/lego-75415-star-wars-helm-kylo-rena",
    image:
      "https://zklockow.pl/img/960/lego-star-wars-75415-helm-kylo-rena-1.jpg",
    alt: "KyloRen",
    series: "StarWars",
  },
  {
    setNumber: 10372,
    year: 2025,
    price: 299,
    url: "https://zklockow.pl/lego-10372-botanicals-hibiskus",
    image: "https://zklockow.pl/img/960/lego-botanicals-10372-hibiskus-1.jpg",
    alt: "Hibiscus",
    series: "Botanicals",
  },
  {
    setNumber: 10372,
    year: 2025,
    price: 179,
    url: "https://zklockow.pl/lego-75408-star-wars-helm-jango-fetta",
    image:
      "https://zklockow.pl/img/960/lego-star-wars-75408-helm-jango-fetta-1.jpg",
    alt: "JangoFett",
    series: "StarWars",
  },
];
